# Generated by Django 3.2.18 on 2026-09-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContextEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('telegram', '텔레그램')], default='telegram', max_length=20)),
                ('origin', models.CharField(choices=[('live', '실시간'), ('export', '내보내기 가져오기')], default='live', max_length=20)),
                ('key', models.CharField(max_length=200, unique=True)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('reply_to_id', models.BigIntegerField(blank=True, null=True)),
                ('reply_to_bot', models.BooleanField(default=False)),
                ('at', models.DateTimeField(db_index=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('author_id', models.BigIntegerField(blank=True, null=True)),
                ('author_name', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('운영진A', '운영진A(대표)'), ('운영진B', '운영진B'), ('운영진C', '운영진C(편집장)'), ('관리자', '관리자'), ('봇', '봇'), ('참여자', '참여자')], default='참여자', max_length=20)),
                ('text', models.TextField(blank=True, help_text='가린 본문만 저장한다')),
                ('redactions', models.JSONField(blank=True, default=dict, help_text='규칙별 가림 건수')),
                ('media', models.CharField(blank=True, max_length=20)),
                ('media_name', models.CharField(blank=True, max_length=200)),
                ('file_id', models.CharField(blank=True, max_length=200)),
                ('forwarded', models.BooleanField(default=False)),
                ('forgotten', models.BooleanField(default=False, help_text='운영진이 지워 달라고 한 기록(내용 비움)')),
            ],
            options={
                'verbose_name': '대화 기록',
                'verbose_name_plural': '대화 기록',
                'ordering': ['at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('운영진A', '운영진A(대표)'), ('운영진B', '운영진B'), ('운영진C', '운영진C(편집장)'), ('관리자', '관리자'), ('봇', '봇'), ('참여자', '참여자')], max_length=20)),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('aliases', models.CharField(blank=True, help_text='내보내기 파일·텔레그램에 보이는 이름, 쉼표로 구분', max_length=300)),
            ],
            options={
                'verbose_name': '대화 참여자 역할',
                'verbose_name_plural': '대화 참여자 역할',
            },
        ),
        migrations.AddIndex(
            model_name='contextentry',
            index=models.Index(fields=['chat_id', 'at'], name='context_con_chat_id_06ce7e_idx'),
        ),
    ]
