# Generated by Django 3.2.18 on 2026-09-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextentry',
            name='media_read_tries',
            field=models.PositiveSmallIntegerField(default=0, help_text='사진 읽기에 실패한 횟수(3번이면 읽지 못함으로)'),
        ),
        migrations.AddField(
            model_name='contextentry',
            name='heading',
            field=models.CharField(blank=True, help_text='노션 구역: 『페이지 제목』 · 구역 제목', max_length=200),
        ),
        migrations.AddField(
            model_name='contextentry',
            name='media_read_at',
            field=models.DateTimeField(blank=True, help_text='사진을 읽은 시각(글자 없는 사진도)', null=True),
        ),
        migrations.AddField(
            model_name='contextentry',
            name='media_text',
            field=models.TextField(blank=True, help_text='사진에서 읽은 글(가림 적용). 첫 줄에 [포스터] 같은 종류'),
        ),
        migrations.AlterField(
            model_name='contextentry',
            name='source',
            field=models.CharField(choices=[('telegram', '텔레그램'), ('notion', '노션')], default='telegram', max_length=20),
        ),
    ]
