# Generated by Django 3.2.18 on 2026-09-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0002_moments'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextentry',
            name='link_read_at',
            field=models.DateTimeField(blank=True, help_text='링크를 읽어 본 시각(못 읽었어도)', null=True),
        ),
        migrations.AddField(
            model_name='contextentry',
            name='link_text',
            field=models.TextField(blank=True, help_text='글 속 유튜브 링크에서 읽은 제목·채널·공개일·설명(가림 적용)'),
        ),
    ]
