sudo: required
#notifications:
#  webhooks: https://coveralls.io/webhook

matrix:
  include:
  - language: node_js
    cache:
      yarn: true
    node_js:
    - '10'
    dist: trusty
    #env:
    #- COVERALLS_PARALLEL=true
    before_install:   # Script to run before install
    - cd frontend
    install:          # Script to install required packages
    - yarn install
    script:           # Script to test your build
    - yarn run lint
    - yarn run test --coverage --watchAll=false
    #after_success:
    #- cat ./coverage/lcov.info | coveralls

  - language: java
    jdk:
    - openjdk8
    dist: trusty
    services:
    - mysql
    - redis-server
    #env:
    #- COVERALLS_PARALLEL=true
    before_install:
    - mysql -e "CREATE DATABASE hantijae_bookstore;"
    - mysql -e "CREATE USER 'davin'@'localhost' IDENTIFIED BY 'hantijae';"
    - mysql -e "GRANT ALL PRIVILEGES ON *.* to 'davin'@'localhost';"
    install:
    #- pip install -r requirements.txt
    script:
    #- pylint --rcfile=./backend/.pylintrc backend --disable='fixme, duplicate-code'
    - cd backend
    - mvn test -B
    #- coverage run --source='.' ./manage.py test
    #- coverage report --fail-under=90
    #- coverage xml
    #after_success:
    #- sonar-scanner
    #- coveralls

