# Generated by Django 3.0.4 on 2020-04-01 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous', models.BooleanField(default=False)),
                ('last_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session')),
            ],
            options={
                'db_table': 'accounts_user',
            },
        ),
    ]
