# Generated by Django 3.0.4 on 2020-04-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200401_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='price',
            field=models.PositiveIntegerField(default=100000),
        ),
    ]
