# Generated by Django 3.0.4 on 2020-04-01 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200401_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookbasket',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='bookbasket',
            name='book',
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='BookBasket',
        ),
    ]
