# Generated by Django 3.0.4 on 2020-04-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_basket_bookbasket'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifiable',
            field=models.BooleanField(default=False),
        ),
    ]
