# Generated by Django 3.0.4 on 2020-04-12 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200407_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='bookbasket',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
