# Generated by Django 3.0.4 on 2020-04-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200412_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='manual',
            field=models.BooleanField(default=False, help_text='직접 입력한 주문'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.IntegerField(choices=[(-1, '유효하지 않음'), (1, '책 담는 중'), (2, '주문 완료'), (3, '입금 확인'), (4, '발송 완료'), (5, '수령 확인')], default=1),
        ),
    ]
