# Generated by Django 3.0.4 on 2020-06-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200414_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='info',
            field=models.CharField(blank=True, help_text='이벤트 등 관련 정보', max_length=200),
        ),
        migrations.AddField(
            model_name='bookbasket',
            name='address',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='bookbasket',
            name='sign',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
