# Generated by Django 3.0.4 on 2020-06-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200607_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookbasket',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='bookbasket',
            name='receiver_phone_number',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
