# Generated by Django 3.2.18 on 2026-09-28 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intake', '0004_fundingcampaign'),
        ('books', '0013_book_cover_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(unique=True)),
                ('measure', models.CharField(blank=True, max_length=300)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WatchQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(max_length=200, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('news', '저자 소식')], max_length=20)),
                ('key', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('happens_on', models.DateField(blank=True, null=True)),
                ('found_at', models.DateTimeField(auto_now_add=True)),
                ('relevant', models.BooleanField(default=False)),
                ('sensitive', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('kit', '신간 홍보 묶음'), ('brief_item', '브리핑 항목')], max_length=20)),
                ('candidate_key', models.CharField(blank=True, max_length=200)),
                ('headline', models.CharField(max_length=300)),
                ('reason', models.TextField(blank=True)),
                ('caution', models.TextField(blank=True)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(default='proposed', max_length=20)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketing_proposals', to='books.book')),
                ('briefing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketing.briefing')),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.signal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HookDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('month', models.PositiveSmallIntegerField()),
                ('day', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField(blank=True, help_text='비우면 매년', null=True)),
                ('memorial', models.BooleanField(default=False, help_text='추모 성격: 판매 권유 금지')),
                ('note', models.CharField(blank=True, max_length=300)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('books', models.ManyToManyField(blank=True, related_name='hook_dates', to='books.Book')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('blog', '블로그 글'), ('instagram', '인스타 글'), ('links', '서점 링크 공지'), ('short', '짧은 소개'), ('letter', '보낼 글')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField()),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('posted_by', models.CharField(blank=True, max_length=100)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.draft')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='marketing.proposal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CopyNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='marketing.draft')),
            ],
        ),
        migrations.CreateModel(
            name='BookProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aladin_item_id', models.CharField(blank=True, max_length=20)),
                ('quiet_until', models.DateField(blank=True, help_text='이 날짜까지 홍보 제안을 하지 않음', null=True)),
                ('quiet_reason', models.CharField(blank=True, help_text='관리자만 봄', max_length=200)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketing', to='books.book')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sales_point', models.PositiveIntegerField()),
                ('short_reviews', models.PositiveIntegerField(default=0)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_snapshots', to='books.book')),
            ],
            options={
                'ordering': ('-date',),
                'unique_together': {('book', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FundingSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.PositiveIntegerField()),
                ('goal', models.PositiveIntegerField(default=0)),
                ('books', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='intake.fundingcampaign')),
            ],
            options={
                'unique_together': {('campaign', 'date')},
            },
        ),
    ]
