# Generated by Django 3.2.18 on 2026-09-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_draftmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('source', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=1000)),
                ('posted_on', models.DateField(blank=True, null=True)),
                ('withdrawal', models.BooleanField(default=False, help_text='철회·취소 공고')),
                ('matched', models.PositiveSmallIntegerField(default=0, help_text='찾은 한티재 책 수')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='signal',
            name='kind',
            field=models.CharField(choices=[('news', '저자 소식'), ('selection', '공공 선정')], max_length=20),
        ),
    ]
