# Generated by Django 3.2.18 on 2026-09-29 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0002_moments'),
        ('marketing', '0002_draftmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='kind',
            field=models.CharField(choices=[('kit', '신간 홍보 묶음'), ('brief_item', '브리핑 항목'), ('now', '주중 제안')], max_length=20),
        ),
        migrations.AlterField(
            model_name='signal',
            name='kind',
            field=models.CharField(choices=[('news', '저자 소식'), ('moment', '대화 속 계기')], max_length=20),
        ),
        migrations.CreateModel(
            name='MomentScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField()),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='context.contextentry')),
            ],
        ),
        migrations.CreateModel(
            name='SignalEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='context.contextentry')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='marketing.signal')),
            ],
            options={
                'unique_together': {('signal', 'entry')},
            },
        ),
    ]
