# Generated by Django 3.2.18 on 2026-09-29 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_selections'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', '페이스북'), ('instagram', '인스타그램')], max_length=20)),
                ('purpose', models.CharField(default='normal', help_text='normal·first(첫 실행)·deep(틈 보충)·manual', max_length=10)),
                ('accounts', models.JSONField(blank=True, default=list, help_text='역할 키 목록')),
                ('limit', models.PositiveSmallIntegerField(default=5, help_text='계정당 글 수')),
                ('apify_run_id', models.CharField(blank=True, max_length=50)),
                ('dataset_id', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(default='starting', max_length=10)),
                ('apify_status', models.CharField(blank=True, max_length=20)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('cap_usd', models.DecimalField(decimal_places=3, max_digits=6)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('stats', models.JSONField(blank=True, default=dict, help_text='계정별 items·valid·errors·new·known·reached·gap·status')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.AlterField(
            model_name='signal',
            name='kind',
            field=models.CharField(choices=[('news', '저자 소식'), ('selection', '공공 선정'), ('social', '운영진 SNS')], max_length=20),
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('account', models.CharField(help_text='역할 키(editor·ceo)', max_length=20)),
                ('post_id', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=1000)),
                ('posted_at', models.DateTimeField()),
                ('text', models.TextField(blank=True, help_text='본인이 쓴 말')),
                ('shared', models.JSONField(blank=True, default=dict, help_text='공유 원문: url, text, author, posted_at')),
                ('link', models.JSONField(blank=True, default=dict, help_text='외부 링크: url, title, source')),
                ('group_key', models.CharField(blank=True, db_index=True, max_length=300)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('judged_at', models.DateTimeField(blank=True, null=True)),
                ('verdict', models.JSONField(blank=True, default=dict)),
                ('text_cleared_at', models.DateTimeField(blank=True, null=True)),
                ('first_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='marketing.socialrun')),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to='marketing.signal')),
            ],
            options={
                'unique_together': {('platform', 'post_id')},
            },
        ),
    ]
