# Generated by Django 3.2.18 on 2026-09-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_moments'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=1000)),
                ('posted_on', models.DateField()),
                ('state', models.CharField(max_length=20)),
                ('tries', models.PositiveSmallIntegerField(default=0, help_text='LLM 판단 실패 횟수(3번이면 건너뜀)')),
                ('verdict', models.JSONField(blank=True, default=dict)),
                ('apply_until', models.DateField(blank=True, help_text='원문과 대조해 확인한 마감일만', null=True)),
                ('preview_at', models.DateTimeField(blank=True, help_text='관리자 1:1 미리보기를 보낸 시각', null=True)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='검수 방에 카드를 보낸 시각', null=True)),
                ('decided_by', models.CharField(blank=True, max_length=100)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reminded_at', models.DateTimeField(blank=True, help_text='마감 이틀 전 알림을 보낸 시각', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
