# Generated by Django 3.2.18 on 2026-09-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_grants'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchquery',
            name='narrow',
            field=models.CharField(blank=True, help_text='검색어에 덧붙이는 조건(동명이인 거르기). 예: (가수 OR 노래 OR 한티재)', max_length=300),
        ),
        migrations.AddField(
            model_name='watchquery',
            name='narrowed_at',
            field=models.DateTimeField(blank=True, help_text='조건을 정한 때(자동·/watch). 비어 있으면 다음 수집 때 자동으로 고른다', null=True),
        ),
    ]
