# Generated by Django 3.2.18 on 2026-09-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_watch_narrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='kind',
            field=models.CharField(choices=[('news', '저자 소식'), ('selection', '공공 선정'), ('social', '운영진 SNS'), ('moment', '대화 속 계기'), ('review', '독자 서평')], max_length=20),
        ),
    ]
