# Generated by Django 3.2.18 on 2026-09-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='placements',
            field=models.JSONField(blank=True, default=list, help_text='[올렸어요] 뒤 봇이 찾은 실제 게시 위치: kind·label·url·id·at (placements.py)'),
        ),
    ]
