# Generated by Django 3.2.18 on 2026-09-30 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_cover_thumbnail'),
        ('marketing', '0009_draft_placements'),
    ]

    operations = [
        migrations.CreateModel(
            name='BnkSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('isbn', models.CharField(max_length=13)),
                ('title', models.CharField(max_length=300)),
                ('kyobo', models.PositiveIntegerField(default=0)),
                ('yes24', models.PositiveIntegerField(default=0)),
                ('aladin', models.PositiveIntegerField(default=0)),
                ('ypbooks', models.PositiveIntegerField(default=0, help_text='영풍문고')),
                ('local', models.PositiveIntegerField(default=0, help_text='지역서점')),
                ('total', models.PositiveIntegerField(default=0)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bnk_sales', to='books.book')),
            ],
            options={
                'unique_together': {('day', 'isbn')},
            },
        ),
    ]
