# Generated by Django 3.2.18 on 2026-09-30 06:35

import re

from django.db import migrations, models

# 예전 편지는 '알리면 좋을 곳' 목록이 본문 머리에 붙어 있었다. 목록을 extra로 떼어 내 본문이 곧 보낼 글이 되게 한다.
HEAD = '알리면 좋을 곳\n'
_SEP = re.compile(r'\n\n보낼 글(?: \((?P<to>[^\n]*)\))?\n(?:제목: (?P<title>[^\n]*)\n\n)?')


def split_letter(title, body):
    """예전 편지 본문(보낼 곳 목록이 본문 머리에 있던 모양) → (제목, 본문, extra). 모양이 다르면 None."""
    if not body.startswith(HEAD):
        return None
    m = _SEP.search(body)
    if not m:
        return None
    lines = body[:m.start()].split('\n')[1:]
    if not all(line.startswith('· ') for line in lines):
        return None  # 머리에 목록 말고 다른 문단이 있으면 잃지 않도록 건드리지 않는다
    places = [line[2:].strip() for line in lines]
    inner = (m.group('title') or '').strip()
    moved = bool(not title and inner)
    extra = {'places': places, 'to': (m.group('to') or '').strip(),
             'legacy': 'brief' if m.group(0) == '\n\n보낼 글\n' else 'kit', 'title_moved': moved}
    return (inner if moved else title), body[m.end():], extra


def join_letter(title, body, extra):
    """split_letter의 반대. 새 코드가 만든 편지(legacy 없음)는 받는 곳이 있으면 신간 모양으로 붙인다."""
    legacy = extra.get('legacy') or ('kit' if extra.get('to') else 'brief')
    moved = extra.get('title_moved', legacy == 'kit' and 'legacy' not in extra)
    places = '\n'.join(f'· {p}' for p in extra.get('places', []))
    if legacy == 'kit':
        inner = title if moved else ''
        return ('' if moved else title), f'{HEAD}{places}\n\n보낼 글 ({extra.get("to", "")})\n제목: {inner}\n\n{body}'
    return title, f'{HEAD}{places}\n\n보낼 글\n{body}'


def forward(apps, schema_editor):
    Draft = apps.get_model('marketing', 'Draft')
    for d in Draft.objects.filter(channel='letter', body__startswith=HEAD):
        out = split_letter(d.title, d.body)
        if out:
            d.title, d.body, d.extra = out[0], out[1], {**(d.extra or {}), **out[2]}
            d.save(update_fields=['title', 'body', 'extra'])


def backward(apps, schema_editor):
    Draft = apps.get_model('marketing', 'Draft')
    for d in Draft.objects.filter(channel='letter'):
        extra = d.extra or {}
        if extra.get('places') or extra.get('to'):
            d.title, d.body = join_letter(d.title, d.body, extra)
            d.save(update_fields=['title', 'body'])


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_bnk_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefing',
            name='notion',
            field=models.JSONField(blank=True, default=dict, help_text='노션 페이지: page·url·state·tries·since·last_try·hub_text'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='shown',
            field=models.JSONField(blank=True, default=list, help_text='검수 방 메시지에 보인 항목(Proposal id) 순서'),
        ),
        migrations.AddField(
            model_name='draft',
            name='extra',
            field=models.JSONField(blank=True, default=dict, help_text='편지: places(알리면 좋을 곳), to(받는 곳)'),
        ),
        migrations.AddField(
            model_name='draft',
            name='notion',
            field=models.JSONField(blank=True, default=dict, help_text='box(📝 상자 블록), title(제목 블록)'),
        ),
        migrations.AddField(
            model_name='draft',
            name='origin',
            field=models.CharField(choices=[('bot', '봇 첫 글'), ('rewrite', '텔레그램 고치기'), ('notion', '노션에서 고침')], default='bot', max_length=10),
        ),
        migrations.AddField(
            model_name='proposal',
            name='notion',
            field=models.JSONField(blank=True, default=dict, help_text='노션: heading(항목 제목 블록) 또는 headings(채널별), 페이지 칸'),
        ),
        migrations.RunPython(forward, backward),
    ]
