# Generated by Django 3.2.18 on 2026-09-30 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_cover_thumbnail'),
        ('marketing', '0010_bnk_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefing',
            name='measure',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.CreateModel(
            name='LoanSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='그 달 1일')),
                ('loans', models.PositiveIntegerField()),
                ('ranking', models.PositiveIntegerField(blank=True, help_text='그 달 전국 대출 순위', null=True)),
                ('taken_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_snapshots', to='books.book')),
            ],
            options={
                'ordering': ('-month',),
                'unique_together': {('book', 'month')},
            },
        ),
    ]
