# Generated by Django 3.2.18 on 2026-09-30 06:35

from django.db import migrations, models


def _origin_sql(apps, schema_editor, action):
    Draft = apps.get_model('marketing', 'Draft')
    q = schema_editor.quote_name
    return f"ALTER TABLE {q(Draft._meta.db_table)} ALTER COLUMN {q(Draft._meta.get_field('origin').column)} {action}"


def set_origin_default(apps, schema_editor):
    """Django는 칸을 더한 뒤 DB 기본값을 지운다. 운영 MySQL은 strict라 origin 없이 넣는 예전 코드(배포 중·코드만 되돌린 뒤)가
    깨지므로 'bot' 기본값을 DB에 남긴다. MySQL에서만(시험 SQLite는 그대로)."""
    if schema_editor.connection.vendor == 'mysql':
        schema_editor.execute(_origin_sql(apps, schema_editor, "SET DEFAULT 'bot'"))


def drop_origin_default(apps, schema_editor):
    if schema_editor.connection.vendor == 'mysql':
        schema_editor.execute(_origin_sql(apps, schema_editor, 'DROP DEFAULT'))


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0011_loans'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefing',
            name='notion',
            field=models.JSONField(blank=True, default=dict, help_text='노션 페이지: page·url·state·tries·since·last_try·hub_text'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='shown',
            field=models.JSONField(blank=True, default=list, help_text='검수 방 메시지에 보인 항목(Proposal id) 순서'),
        ),
        migrations.AddField(
            model_name='draft',
            name='extra',
            field=models.JSONField(blank=True, default=dict, help_text='편지: places(알리면 좋을 곳), to(받는 곳)'),
        ),
        migrations.AddField(
            model_name='draft',
            name='notion',
            field=models.JSONField(blank=True, default=dict, help_text='box(📝 상자 블록), title(제목 블록)'),
        ),
        migrations.AddField(
            model_name='draft',
            name='origin',
            field=models.CharField(choices=[('bot', '봇 첫 글'), ('rewrite', '텔레그램 고치기'), ('notion', '노션에서 고침')], default='bot', max_length=10),
        ),
        migrations.AddField(
            model_name='proposal',
            name='notion',
            field=models.JSONField(blank=True, default=dict, help_text='노션: heading(항목 제목 블록) 또는 headings(채널별), 페이지 칸'),
        ),
        migrations.RunPython(set_origin_default, drop_origin_default),
    ]
