# Generated by Django 3.2.18 on 2026-10-03 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_book_ebook'),
        ('marketing', '0013_split_letters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_id', models.CharField(max_length=40, unique=True)),
                ('channel', models.CharField(choices=[('facebook', '페이스북'), ('instagram', '인스타그램')], max_length=20)),
                ('post_id', models.CharField(help_text='페북 글 번호(페이지_글) 또는 인스타 글 번호', max_length=80)),
                ('ig_media_id', models.CharField(blank=True, help_text='광고가 인스타에 쓴 글 번호(있으면)', max_length=40)),
                ('post_url', models.URLField(blank=True, max_length=500)),
                ('post_text', models.CharField(blank=True, help_text='글 앞부분', max_length=200)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('first_day', models.DateField(blank=True, help_text='지출이 있었던 첫날(광고 계정 시간대)', null=True)),
                ('last_day', models.DateField(blank=True, help_text='지출이 있었던 끝날', null=True)),
                ('spend', models.IntegerField(default=0, help_text='원')),
                ('impressions', models.IntegerField(default=0)),
                ('reach', models.IntegerField(default=0, help_text='본 사람 수(중복 없음, 전체 기간)')),
                ('clicks', models.IntegerField(default=0, help_text="'더 보기'·사진 누름까지")),
                ('link_clicks', models.IntegerField(default=0)),
                ('reactions', models.IntegerField(default=0)),
                ('engagement', models.IntegerField(default=0)),
                ('totals_at', models.DateTimeField(blank=True, help_text='전체 합계를 마지막으로 읽은 때', null=True)),
                ('card', models.CharField(choices=[('pending', '보낼 차례'), ('sent', '보냄'), ('skipped', '안 보냄')], default='pending', max_length=10)),
                ('card_sent_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_ads', to='books.book')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('spend', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('link_clicks', models.IntegerField(default=0)),
                ('reactions', models.IntegerField(default=0)),
                ('engagement', models.IntegerField(default=0)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='marketing.ad')),
            ],
            options={
                'unique_together': {('ad', 'day')},
            },
        ),
    ]
