# Generated by Django 3.2.18 on 2026-10-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0014_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='book_asked_at',
            field=models.DateTimeField(blank=True, help_text='AI에게 어느 책인지 물은 때(광고마다 한 번)', null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='book_title',
            field=models.CharField(blank=True, help_text='사이트 도서 목록에 아직 없는 책 제목(북펀드 등). 사이트 책이 이어지면 비운다', max_length=200),
        ),
    ]
