export const bookConstants = {
  GET_BOOK_SUCCESS: 'GET_BOOK_SUCCESS',
  GET_BOOK_FAILURE: 'GET_BOOK_FAILURE',
  GET_BOOKS_SUCCESS: 'GET_BOOKS_SUCCESS',
  GET_BOOKS_FAILURE: 'GET_BOOKS_FAILURE',
  GET_BOOKS_BY_CATEGORY_SUCCESS: 'GET_BOOKS_BY_CATEGORY_SUCCESS',
  GET_BOOKS_BY_CATEGORY_FAILURE: 'GET_BOOKS_BY_CATEGORY_FAILURE',
};

export const categoryConstants = {
  GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',
};

export const seriesConstants = {
  GET_SERIES_SUCCESS: 'GET_SERIES_SUCCESS',
  GET_SERIES_FAILURE: 'GET_SERIES_FAILURE',
  GET_ALL_SERIES_SUCCESS: 'GET_ALL_SERIES_SUCCESS',
  GET_ALL_SERIES_FAILURE: 'GET_AlL_SERIES_FAILURE',
};

export const userConstants = {
  LOGIN_SUCCESS: 'GET_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'GET_LOGIN_FAILURE',
  SIGNUP_SUCCESS: 'GET_SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'GET_SIGNUP_FAILURE',
  LOGOUT_SUCCESS: 'GET_LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'GET_LOGOUT_FAILURE',
  GET_ME_SUCCESS: 'GET_ME_SUCCESS',
  GET_ME_FAILURE: 'GET_ME_FAILURE',
};

export const basketActions = {
  POST_BOOK_SUCCESS: 'POST_BOOK_SUCCESS',
  POST_BOOK_FAILURE: 'POST_BOOK_FAILURE',
  POST_BOOK_FAILURE_MAX_BOOK: 'POST_BOOK_FAILURE_MAX_BOOK',
  DELETE_BOOK_SUCCESS: 'DELETE_BOOK_SUCCESS',
  DELETE_BOOK_FAILURE: 'DELETE_BOOK_FAILURE',
  GET_BASKET_SUCCESS: 'GET_BASKET_SUCCESS',
  GET_BASKET_FAILURE: 'GET_BASKET_FAILURE',
};

export const stateActions = {
  OPEN_LOGIN_MODAL: 'OPEN_LOGIN_MODAL',
  CLOSE_LOGIN_MODAL: 'CLOSE_LOGIN_MODAL',
  OPEN_FULL_BASKET_MODAL: 'OPEN_FULL_BASKET_MODAL',
  CLOSE_FULL_BASKET_MODAL: 'CLOSE_FULL_BASKET_MODAL',
  OPEN_BASKET_INFO_MODAL: 'OPEN_BASKET_INFO_MODAL',
  CLOSE_BASKET_INFO_MODAL: 'CLOSE_BASKET_INFO_MODAL',
};
