export const bookConstants = {
  GET_BOOK_SUCCESS: 'GET_BOOK_SUCCESS',
  GET_BOOK_FAILURE: 'GET_BOOK_FAILURE',
  GET_BOOKS_SUCCESS: 'GET_BOOKS_SUCCESS',
  GET_BOOKS_FAILURE: 'GET_BOOKS_FAILURE',
  GET_BOOKS_BY_CATEGORY_SUCCESS: 'GET_BOOKS_BY_CATEGORY_SUCCESS',
  GET_BOOKS_BY_CATEGORY_FAILURE: 'GET_BOOKS_BY_CATEGORY_FAILURE',
};

export const categoryConstants = {
  GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',
};

export const seriesConstants = {
  GET_SERIES_SUCCESS: 'GET_SERIES_SUCCESS',
  GET_SERIES_FAILURE: 'GET_SERIES_FAILURE',
  GET_ALL_SERIES_SUCCESS: 'GET_ALL_SERIES_SUCCESS',
  GET_ALL_SERIES_FAILURE: 'GET_AlL_SERIES_FAILURE',
};
