# Generated by Django 3.0.4 on 2020-03-29 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=100)),
                ('given_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=1500)),
                ('phone_number', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'books_author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(max_length=1000)),
                ('short_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('full_price', models.PositiveSmallIntegerField()),
                ('price', models.PositiveSmallIntegerField()),
                ('isbn', models.CharField(max_length=200)),
                ('page_count', models.PositiveSmallIntegerField()),
                ('size', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'books_book',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('category_type', models.IntegerField(choices=[(1, 'normal'), (2, 'series')])),
            ],
            options={
                'db_table': 'books_category',
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_type', models.IntegerField(choices=[(1, 'normal')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.Author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='books.Book')),
            ],
            options={
                'db_table': 'books_bookauthor',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.Category'),
        ),
    ]
