# Generated by Django 3.0.4 on 2020-04-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200330_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(db_index=True),
        ),
    ]
