# Generated by Django 3.0.4 on 2020-04-12 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200401_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
