# Generated by Django 3.0.4 on 2020-05-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20200415_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='aladin_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='book',
            name='interpark_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='book',
            name='kyobo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='book',
            name='yes24_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='author_type',
            field=models.IntegerField(choices=[(1, '저자'), (2, '번역자'), (3, '기획자'), (4, '엮은이')], default=1),
        ),
    ]
