# Generated by Django 3.1.13 on 2022-09-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20200503_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookseries',
            name='index',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
