# Generated by Django 3.1.14 on 2022-09-11 04:04

import books.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20220910_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=books.models.Book.cover_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image_3d',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=books.models.Book.cover_image_3d_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
