# Generated by Django 3.2.18 on 2026-09-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20220911_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='사이트 공개 여부 (해제 = 검수 중 초안)'),
        ),
    ]
