# Generated by Django 3.2.18 on 2026-09-27 15:34

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_thumbnail',
            field=models.FileField(blank=True, editable=False, help_text='목록 카드용 축소 표지 (표지를 바꾸면 자동 생성)', max_length=255, null=True, upload_to=books.models.Book.cover_thumbnail_path),
        ),
    ]
