# Generated by Django 3.2.18 on 2026-10-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_cover_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ebook_aladin_url',
            field=models.URLField(blank=True, help_text='알라딘 전자책 상품 주소', max_length=500),
        ),
        migrations.AddField(
            model_name='book',
            name='ebook_isbn',
            field=models.CharField(blank=True, help_text='전자책 ISBN (EPUB)', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='ebook_kyobo_url',
            field=models.URLField(blank=True, help_text='교보문고 전자책 상품 주소', max_length=500),
        ),
        migrations.AddField(
            model_name='book',
            name='ebook_ridi_url',
            field=models.URLField(blank=True, help_text='리디 상품 주소', max_length=500),
        ),
        migrations.AddField(
            model_name='book',
            name='ebook_yes24_url',
            field=models.URLField(blank=True, help_text='예스24 전자책 상품 주소', max_length=500),
        ),
    ]
