# Generated by Django 3.2.18 on 2026-09-27 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(blank=True, help_text='첫 화면 맨 위 한 줄 (60자 안쪽 권장)', max_length=200)),
                ('link_url', models.URLField(blank=True, max_length=500)),
                ('link_label', models.CharField(default='자세히 보기', max_length=30)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, help_text='비우면 내릴 때까지', null=True)),
                ('state', models.CharField(choices=[('asking', '내용 기다리는 중'), ('draft', '미리보기'), ('posted', '게시 중'), ('removed', '내림')], default='posted', max_length=10)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('message_id', models.BigIntegerField(blank=True, help_text='봇 대화에서 답장받을 메시지', null=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': '알림 띠',
                'verbose_name_plural': '알림 띠',
                'ordering': ('-id',),
            },
        ),
    ]
