# Generated by Django 3.2.18 on 2026-09-27 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_cover_thumbnail'),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(choices=[('aladin', '알라딘'), ('yes24', 'YES24'), ('kyobo', '교보문고')], max_length=10)),
                ('referrer_host', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_clicks', to='books.book')),
            ],
            options={
                'verbose_name': '서점 클릭',
                'verbose_name_plural': '서점 클릭',
                'ordering': ('-id',),
            },
        ),
    ]
