# Generated by Django 3.2.18 on 2026-09-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_storeclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='pending',
            field=models.JSONField(blank=True, help_text='봇: 반영을 기다리는 수정안 (snapshot 형식)', null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='previous',
            field=models.JSONField(blank=True, help_text='봇: 마지막 반영 전 값 {values, at} — 되돌리기용', null=True),
        ),
    ]
