# Generated by Django 3.2.18 on 2026-10-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_notice_pending_previous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeclick',
            name='store',
            field=models.CharField(choices=[('aladin', '알라딘'), ('yes24', 'YES24'), ('kyobo', '교보문고'), ('e_aladin', '알라딘 전자책'), ('e_yes24', 'YES24 전자책'), ('e_kyobo', '교보문고 전자책'), ('ridi', '리디')], max_length=10),
        ),
    ]
