# Generated by Django 3.2.18 on 2026-09-25 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0012_book_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('extracting', '추출 중'), ('review', '검수 중'), ('published', '공개됨'), ('discarded', '폐기'), ('failed', '실패')], default='extracting', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('extracted', models.JSONField(blank=True, default=dict, help_text='LLM 원출력 + _unresolved 목록')),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('files', models.JSONField(blank=True, default=dict, help_text='선택된 보도자료·표지와 입체 대안 경로')),
                ('source_text', models.TextField(blank=True, help_text='로컬 추출 원문 (원문 대조·변경분 프롬프트용)')),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('message_id', models.BigIntegerField(blank=True, help_text='검수 메시지 ID (답장 대상 식별)', null=True)),
                ('notion_page_id', models.CharField(blank=True, max_length=100)),
                ('error', models.TextField(blank=True)),
                ('book', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_draft', to='books.book')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntakeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('drive', '드라이브'), ('telegram', '텔레그램')], max_length=20)),
                ('drive_folder_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('title', models.CharField(help_text='폴더명 또는 텔레그램 요청 설명', max_length=500)),
                ('path', models.CharField(blank=True, help_text='드라이브 경로 또는 tg:<chat>:<message>', max_length=1000)),
                ('fingerprint', models.CharField(blank=True, max_length=64)),
                ('stable_since', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('seen', '감지됨'), ('baseline', '기준선(무시)'), ('queued', '처리 대기'), ('processing', '처리 중'), ('processed', '처리 완료'), ('ignored', '건너뜀'), ('failed', '실패')], default='seen', max_length=20)),
                ('local_dir', models.CharField(blank=True, help_text='텔레그램으로 받은 파일 저장 위치', max_length=1000)),
                ('requested_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('kind', models.CharField(choices=[('family', '가족 그룹'), ('admin', '관리자 1:1')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PendingPatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_version', models.PositiveIntegerField()),
                ('changes', models.JSONField(default=list, help_text='[{field, new_value}]')),
                ('questions', models.JSONField(default=list)),
                ('request_text', models.TextField(blank=True)),
                ('requested_by', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('proposed', '제안'), ('applied', '반영'), ('cancelled', '취소'), ('stale', '만료')], default='proposed', max_length=20)),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patches', to='intake.bookdraft')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DraftRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('changes', models.JSONField(default=list, help_text='[{field, old, new}]')),
                ('request_text', models.TextField(blank=True)),
                ('requested_by', models.CharField(blank=True, max_length=200)),
                ('reverted', models.BooleanField(default=False)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='intake.bookdraft')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bookdraft',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drafts', to='intake.intakesource'),
        ),
    ]
