# Generated by Django 3.2.18 on 2026-09-27 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_is_published'),
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.CharField(help_text='한 번에 보낸 묶음 이름', max_length=100)),
                ('seq', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True, help_text='근거 (노션·사이트·서점 값)')),
                ('notion_page_id', models.CharField(blank=True, max_length=100)),
                ('options', models.JSONField(default=list, help_text="[{label, set: {항목: 값}}] — set 이 비면 '그대로 두기'")),
                ('before', models.JSONField(default=dict, help_text='게시 시점 값 {항목: {notion, site}} — 덮어쓰기 방지 기준')),
                ('status', models.CharField(choices=[('pending', '대기'), ('applied', '반영'), ('kept', '그대로'), ('stale', '값이 바뀌어 중단')], default='pending', max_length=20)),
                ('chosen', models.SmallIntegerField(blank=True, null=True)),
                ('changed', models.JSONField(blank=True, default=list, help_text='실제로 바꾼 값 [[곳, 항목, 전, 후]]')),
                ('decided_by', models.CharField(blank=True, max_length=200)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, help_text='가족이 답장으로 남긴 메모')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='books.book')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
