# Generated by Django 3.2.18 on 2026-09-27 13:01

from django.db import migrations, models

# 대화방 종류·경고 대상을 역할 이름으로 바꾼다. 이전에 저장된 값을 새 값으로 옮긴다.
OLD_KIND, NEW_KIND = 'family', 'reviewers'
OLD_AUDIENCE, NEW_AUDIENCE = 'family', 'reviewer'


def _move(apps, kind_from, kind_to, audience_from, audience_to):
    TelegramChat = apps.get_model('intake', 'TelegramChat')
    BookDraft = apps.get_model('intake', 'BookDraft')
    TelegramChat.objects.filter(kind=kind_from).update(kind=kind_to)

    def fix(warnings):
        return [dict(w, audience=audience_to) if w.get('audience') == audience_from else w for w in warnings or []]

    for draft in BookDraft.objects.all():
        extracted = dict(draft.extracted or {})
        if '_notes' in extracted:
            extracted['_notes'] = fix(extracted['_notes'])
        draft.warnings, draft.extracted = fix(draft.warnings), extracted
        draft.save(update_fields=['warnings', 'extracted'])


def forwards(apps, schema_editor):
    _move(apps, OLD_KIND, NEW_KIND, OLD_AUDIENCE, NEW_AUDIENCE)


def backwards(apps, schema_editor):
    _move(apps, NEW_KIND, OLD_KIND, NEW_AUDIENCE, OLD_AUDIENCE)


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_review_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewitem',
            name='note',
            field=models.TextField(blank=True, help_text='검수자가 답장으로 남긴 메모'),
        ),
        migrations.AlterField(
            model_name='telegramchat',
            name='kind',
            field=models.CharField(choices=[('reviewers', '검수 그룹'), ('admin', '관리자 1:1')], max_length=20),
        ),
        migrations.RunPython(forwards, backwards),
    ]
