# Generated by Django 3.2.18 on 2026-09-27 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_storeclick'),
        ('intake', '0003_role_based_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('aladin', '알라딘 북펀드'), ('tumblbug', '텀블벅')], max_length=20)),
                ('external_id', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='펀딩이 닫히는 순간(마감일 다음 날 0시, 한국 시간)', null=True)),
                ('is_ours', models.BooleanField(default=False)),
                ('notice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='web.notice')),
            ],
            options={
                'unique_together': {('platform', 'external_id')},
            },
        ),
    ]
