runtime: java
env: flex
runtime_config:
  jdk: openjdk9
resources:
  memory_gb: 2.0
env_variables:
  SPRING_PROFILES_ACTIVE: "gcp,mysql"
handlers:
  - url: /.*
    script: this field is required, but ignored
manual_scaling:
  instances: 1
beta_settings:
  cloud_sql_instances: hantijae:asia-northeast1:hantijae-bookstore=tcp:3306